# Generated by Django 4.0.2 on 2022-02-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('s_major', models.CharField(max_length=50)),
                ('s_age', models.IntegerField(default=20)),
                ('s_grade', models.IntegerField(default=1)),
                ('s_gender', models.CharField(max_length=50)),
            ],
        ),
    ]
