# Generated by Django 4.0.2 on 2022-02-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='s_gander',
            new_name='s_gender',
        ),
    ]
